language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

# command to install dependencies
install: "pip install lxml"

script:
    - ./setup.py test
    - ./setup.py install --root=/tmp/install-root
    # prevent repoman tests from trying to fetch metadata.xsd
    - mkdir -p /tmp/install-root/usr/lib/portage/cnf
    - cp repoman/cnf/metadata.xsd /tmp/install-root/usr/lib/portage/cnf/
    - sudo rsync -a /tmp/install-root/. /
    - python -b -Wd -m portage.tests.runTests
    # repoman test block
    - cd repoman
    - ./setup.py test
    - ./setup.py install --root=/tmp/install-root
    - cd ..
    - sudo rsync -a /tmp/install-root/. /
    - python -b -Wd -m repoman.tests.runTests
